# Generated by Django 4.2.7 on 2023-11-22 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/images"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="qr_codes/images"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "ssid",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="NetworkName",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="WifiPassword",
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="NetworkType",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
