# Generated by Django 4.2.7 on 2023-11-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="one time password"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="otp_expiration_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="otp exipration time"
            ),
        ),
    ]
