# Generated by Django 4.2.7 on 2023-11-16 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_user_otp_alter_user_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
    ]
