# Generated by Django 4.2.7 on 2023-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_user_created_at_user_updated_at_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="one time password",
                    ),
                ),
            ],
        ),
    ]
